server:
  servlet:
    context-path: /im
  port: 8888

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: im
  main:
    allow-bean-definition-overriding: true

mysql:
  datasource:
    ds0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.25.133:3306/test?useSSL=false
      username: mysql
      password: 123456
      initialSize: 10
      maxActive: 20
      minIdle: 10
      maxWait: 5000
      poolPreparedStatements: false
      validationQuery: select 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      filters: log4j,stat

zookeeper:
  url: 172.16.25.133:2181
  app-root: /im